---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: shellyctl
  name: shellyctl

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shellyctl-prom
  namespace: shellyctl
data:
  shellyctl-prom.yaml: |
    bind-port: 19090
    mdns-search: true
    log-level: debug

---  
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: shellyctl-prom
  name: shellyctl-prom
  namespace: shellyctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shellyctl-prom
  template:
    metadata:
      annotations:
        prometheus.io/port: "19090"
        prometheus.io/scrape: "true"
      labels:
        app: shellyctl-prom
    spec:
      containers:
      - command:
        - /bin/shellyctl
        - prometheus
        env:
        - name: SHELLYCTL_CONFIG
          value: /run/shellyctl/shellyctl-prom.yaml
        image: ghcr.io/jcodybaker/shellyctl:latest
        imagePullPolicy: Always
        name: shellyctl
        ports:
        - containerPort: 19090
          hostPort: 19090
          protocol: TCP
        volumeMounts:
        - mountPath: /run/shellyctl
          name: config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: shellyctl-prom
        name: config
