# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build AMD64
      run: GOOS=linux GOARCH=amd64 go build -o shellyctl_linux_amd64

    - name: Build AMD64
      run: GOOS=linux GOARCH=arm64 go build -o shellyctl_linux_arm64

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o shellyctl_windows_arm64

    - name: Test
      run: go test -v ./...

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: 
        - shellyctl_amd64
        - shellyctl_arm64